name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install Shimakaze.Struct.Csf dependencies
      run: dotnet restore ./src/Shimakaze.Struct.Csf/
    - name: Build Shimakaze.Struct.Csf
      run: dotnet build --configuration Release --no-restore ./src/Shimakaze.Struct.Csf/
      
    - name: Install Shimakaze.Struct.Csf.Json dependencies
      run: dotnet restore ./src/Shimakaze.Struct.Csf.Json/
    - name: Build Shimakaze.Struct.Csf.Json
      run: dotnet build --configuration Release --no-restore ./src/Shimakaze.Struct.Csf.Json/
      
#    - name: Test
#      run: dotnet test --no-restore --verbosity normal
